"""placeholder

Revision ID: 57539722e5cf
Revises: c1b5abada09c
Create Date: 2019-12-03 00:55:16.012247

"""

# revision identifiers, used by Alembic.
revision = '57539722e5cf'
down_revision = '9f8da66547c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
